SELECT H.HACKER_ID, H.NAME, COUNT(C.CHALLENGE_ID) AS CNT
FROM HACKERS H
JOIN CHALLENGES C ON H.HACKER_ID = C.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME
HAVING CNT = (
    SELECT MAX(CNT2) 
    FROM (
        SELECT COUNT(CHALLENGE_ID) AS CNT2
        FROM CHALLENGES
        GROUP BY HACKER_ID
    ) T
)
ORDER BY H.HACKER_ID;