SELECT H.HACKER_ID, H.NAME, SUM(MAXSCORE) AS TOTAL_SCORE
FROM HACKERS H
JOIN (
    SELECT HACKER_ID, CHALLENGE_ID, MAX(SCORE) AS MAXSCORE
    FROM SUBMISSIONS
    GROUP BY HACKER_ID, CHALLENGE_ID
) S ON H.HACKER_ID = S.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME
HAVING TOTAL_SCORE > 0
ORDER BY TOTAL_SCORE DESC, H.HACKER_ID;