SELECT CASE
       WHEN G.GRADE >= 8 THEN S.NAME
       ELSE 'NULL' END,G.GRADE,S.MARKS
       FROM STUDENTS S,GRADES G
       WHERE S.MARKS >= MIN_MARK AND S.MARKS <=MAX_MARK
       ORDER BY G.GRADE DESC,S.NAME,S.MARKS;