SELECT H.HACKER_ID, H.NAME
FROM HACKERS H
JOIN CHALLENGES C ON H.HACKER_ID = C.HACKER_ID
JOIN SUBMISSIONS S ON C.CHALLENGE_ID = S.CHALLENGE_ID
WHERE S.SCORE = (SELECT MAX(SCORE) 
                 FROM SUBMISSIONS 
                 WHERE CHALLENGE_ID = C.CHALLENGE_ID)
GROUP BY H.HACKER_ID, H.NAME
HAVING COUNT(DISTINCT C.CHALLENGE_ID) > 1
ORDER BY H.HACKER_ID;